include:
  - component: $CI_SERVER_FQDN/to-be-continuous/node/gitlab-ci-node@5.3.0
    inputs:
      image: "node:24-bookworm"
      lint-enabled: "true"

  - component: $CI_SERVER_FQDN/to-be-continuous/docker/gitlab-ci-docker@8.3.0
    inputs:
      file: "docker/Dockerfile"

  - component: $CI_SERVER_FQDN/to-be-continuous/playwright/gitlab-ci-playwright@1.9.0
    inputs:
      project-dir: "src/frontend/tests/e2e"
      review-enabled: "true"

stages:
  - build
  - test
  - package-build
  - package-test
  - publish
