node-build:
  stage: build
  image: node:24-bookworm
  script:
    - npm install
    - npm run --workspaces build
    - npm run --workspaces test

include:
  - component: $CI_SERVER_FQDN/to-be-continuous/docker/gitlab-ci-docker@8.3.0
    inputs:
      file: "docker/Dockerfile"
      build-args: "--platform linux/amd64 --platform linux/arm64"
      trivy-disabled: "true"
      sbom-disabled: "true"

docker-buildah-build:
  tags:
    - buildah

stages:
  - build
  - test
  - package-build
  - package-test
  - publish
